// The smooth scroll zoom algorithm (sigmoid scaling, device detection,
// C1-continuous easing) is adapted from MapLibre GL JS's ScrollZoomHandler.
// Most of the original comments are kept.
// Original source: https://github.com/maplibre/maplibre-gl-js
// File: src/ui/handler/scroll_zoom.ts
//
// Copyright (c) 2023, MapLibre contributors.
// Licensed under the BSD-3-Clause License.
// See https://github.com/maplibre/maplibre-gl-js/blob/main/LICENSE.txt
//
// _UnitBezier is adapted from https://github.com/mapbox/unitbezier, which is in
// turn adapted from WebKit.
//
// Copyright (C) 2008 Apple Inc.
// Licensed under the BSD-2-Clause License.
// See https://github.com/mapbox/unitbezier/blob/master/LICENSE

import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/gestures.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_map/flutter_map.dart';

/// Cubic bezier curve, implicit first and last control points are (0,0) and (1,1).
class _UnitBezier {
  final double _cx;
  final double _bx;
  final double _ax;
  final double _cy;
  final double _by;
  final double _ay;

  _UnitBezier(double p1x, double p1y, double p2x, double p2y)
      : _cx = 3.0 * p1x,
        _bx = 3.0 * (p2x - p1x) - 3.0 * p1x,
        _ax = 1.0 + 3.0 * p1x - 3.0 * p2x,
        _cy = 3.0 * p1y,
        _by = 3.0 * (p2y - p1y) - 3.0 * p1y,
        _ay = 1.0 + 3.0 * p1y - 3.0 * p2y;

  // `ax t^3 + bx t^2 + cx t` expanded using Horner's rule.
  double _sampleCurveX(double t) => ((_ax * t + _bx) * t + _cx) * t;
  double _sampleCurveY(double t) => ((_ay * t + _by) * t + _cy) * t;
  double _sampleCurveDerivativeX(double t) =>
      (3.0 * _ax * t + 2.0 * _bx) * t + _cx;

  double _solveCurveX(double x) {
    const epsilon = 1e-6;

    var t = x;

    // First try a few iterations of Newton's method - normally very fast.
    for (var i = 0; i < 8; i++) {
      final x2 = _sampleCurveX(t) - x;
      if (x2.abs() < epsilon) return t;

      final d2 = _sampleCurveDerivativeX(t);
      if (d2.abs() < epsilon) break;

      t -= x2 / d2;
    }

    // Fall back to the bisection method for reliability.
    var t0 = 0.0;
    var t1 = 1.0;
    t = x;

    for (var i = 0; i < 20; i++) {
      final x2 = _sampleCurveX(t);
      if ((x2 - x).abs() < epsilon) return t;

      if (x > x2) {
        t0 = t;
      } else {
        t1 = t;
      }

      t = (t0 - t1) * 0.5 + t0;
    }
    return t;
  }

  double solve(double x) => _sampleCurveY(_solveCurveX(x));
}

typedef _EasingFn = double Function(double t);

_EasingFn _bezier(double p1x, double p1y, double p2x, double p2y) {
  final b = _UnitBezier(p1x, p1y, p2x, p2y);
  return b.solve;
}

final _EasingFn _defaultEasing = _bezier(0.25, 0.1, 0.25, 1);

enum _ScrollType { wheel, trackpad }

/// Scroll zoom handler ported from MapLibre GL JS.
///
/// Mouse wheel events produce discrete ticks that get smoothed with
/// C¹-continuous bezier easing curves. Trackpad events are applied directly
/// since the hardware already provides fine-grained continuous input.
///
/// When [ScrollZoomOptions.smoothZooming] is `false`, falls back to
/// snapping immediately to the new zoom level.
class ScrollZoomHandler {
  final MapControllerImpl _controller;
  final TickerProvider _vsync;

  Ticker? _ticker;
  bool _tickerActive = false;

  // deltaY value for mouse wheel identification
  static const double _wheelZoomDelta = 4.000244140625;
  _ScrollType? _type;
  double _lastValue = 0;
  int _lastWheelEventTime = 0;
  Timer? _timeout;
  Offset? _pendingEventPosition;

  double _delta = 0;

  double? _startZoom;
  double? _targetZoom;
  Offset _cursorPosition = Offset.zero;

  _EasingFn? _easing;
  _PrevEase? _prevEase;

  // upper bound on how much we scale the map in any single render frame; this
  // is used to limit zoom rate in the case of very fast scrolling
  static const double _maxScalePerFrame = 2;

  // Minimum time difference value to be used for calculating zoom easing in renderFrame();
  // this is used to normalise very fast (typically 0 to 0.3ms) repeating lastWheelEventTimeDiff
  // values generated by Chromium based browsers during fast scrolling wheel events.
  static const int _wheelEventTimeDiffAdjustment = 5;

  /// Create a new [ScrollZoomHandler].
  ScrollZoomHandler({
    required MapControllerImpl controller,
    required TickerProvider vsync,
  })  : _controller = controller,
        _vsync = vsync;

  MapCamera get _camera => _controller.camera;
  MapOptions get _options => _controller.options;
  InteractionOptions get _interactionOptions => _options.interactionOptions;
  ScrollZoomOptions get _zoomOptions => _interactionOptions.scrollZoomOptions;
  int get _animationDurationMs => _zoomOptions.animationDuration.inMilliseconds;

  /// Dispose animations and timers.
  void dispose() {
    _timeout?.cancel();
    _ticker?.dispose();
    _ticker = null;
  }

  /// Handle a pointer scroll event.
  void onPointerSignal(PointerScrollEvent event) {
    if (!InteractiveFlag.hasScrollWheelZoom(_interactionOptions.flags)) {
      return;
    }
    if (event.scrollDelta.dy == 0) return;

    if (_zoomOptions.smoothZooming) {
      _doSmoothZoom(event);
    } else {
      _doSnapZoom(event);
    }
  }

  /// Snap zoom: apply zoom change immediately.
  void _doSnapZoom(PointerScrollEvent event) {
    final minZoom = _options.minZoom ?? 0.0;
    final maxZoom = _options.maxZoom ?? double.infinity;
    final newZoom = (_camera.zoom -
            event.scrollDelta.dy * _interactionOptions.scrollWheelVelocity)
        .clamp(minZoom, maxZoom);
    final newCenter = _camera.focusedZoomCenter(
      event.localPosition,
      newZoom,
    );
    _controller.moveRaw(
      newCenter,
      newZoom,
      hasGesture: true,
      source: MapEventSource.scrollWheel,
    );
  }

  /// Smooth zoom: accumulate delta and animate.
  void _doSmoothZoom(PointerScrollEvent event) {
    final value = event.scrollDelta.dy;
    final currentTime = currentTimestamp().millisecondsSinceEpoch;
    final timeDelta = currentTime - _lastWheelEventTime;

    _lastWheelEventTime = currentTime;
    _cursorPosition = event.localPosition;

    if (value != 0 && (value % _wheelZoomDelta) == 0) {
      // This one is definitely a mouse wheel event.
      _type = _ScrollType.wheel;
    } else if (value != 0 && value.abs() < 4) {
      // This one is definitely a trackpad event because it is so small.
      _type = _ScrollType.trackpad;
      if (_timeout != null) {
        _timeout!.cancel();
        _timeout = null;
        _delta -= _lastValue;
      }
    } else if (timeDelta > 400) {
      // New scroll action, unknown device type. Delay 40ms to see if more
      // events arrive (which would indicate trackpad).
      _type = null;
      _lastValue = value;
      _pendingEventPosition = event.localPosition;
      _timeout = Timer(const Duration(milliseconds: 40), () {
        _timeout = null;
        _type = _ScrollType.wheel;
        _lastWheelEventTime = currentTimestamp().millisecondsSinceEpoch;
        _delta -= _lastValue;
        _cursorPosition = _pendingEventPosition!;
        _ensureAnimating();
      });
      return;
    } else if (_type == null) {
      // This is a repeating event, but we don't know the type of event just yet.
      // If the delta per time is small, we assume it's a fast trackpad; otherwise we switch into wheel mode.
      _type = ((timeDelta * value).abs() < 200)
          ? _ScrollType.trackpad
          : _ScrollType.wheel;

      // Make sure our delayed event isn't fired again, because we accumulate
      // the previous event (which was less than 40ms ago) into this event.
      if (_timeout != null) {
        _timeout!.cancel();
        _timeout = null;
        _delta -= _lastValue;
      }
    }

    // Only fire the callback if we actually know what type of scrolling device the user uses.
    if (_type != null) {
      _delta -= value;
      _ensureAnimating();
    }
  }

  void _ensureAnimating() {
    if (_tickerActive) return;

    _ticker ??= _vsync.createTicker(_onTick);
    if (!_ticker!.isActive) {
      _ticker!.start();
    }
    _tickerActive = true;
  }

  void _onTick(Duration elapsed) {
    _renderFrame();
  }

  void _renderFrame() {
    final minZoom = _options.minZoom ?? 0.0;
    final maxZoom = _options.maxZoom ?? double.infinity;

    // if we've had scroll events since the last render frame, consume the
    // accumulated delta, and update the target zoom level accordingly
    if (_delta != 0) {
      // For trackpad events and single mouse wheel ticks, use the default zoom rate
      final zoomRate =
          (_type == _ScrollType.wheel && _delta.abs() > _wheelZoomDelta)
              ? _zoomOptions.wheelZoomRate
              : _zoomOptions.trackpadZoomRate;

      // Scale by sigmoid of scroll wheel delta so the map responds to small scrolls and compresses large scrolls
      var scale =
          _maxScalePerFrame / (1 + math.exp(-(_delta * zoomRate).abs()));

      if (_delta < 0 && scale != 0) {
        scale = 1 / scale;
      }

      final fromZoom = _targetZoom ?? _camera.zoom;
      final fromScale = math.pow(2, fromZoom);
      final newZoom = math.log(fromScale * scale) / math.ln2;
      _targetZoom = newZoom.clamp(minZoom, maxZoom);

      // if this is a mouse wheel, refresh the starting zoom and easing
      // function we're using to smooth out the zooming between wheel events
      if (_type == _ScrollType.wheel) {
        _startZoom = _camera.zoom;
        _easing = _smoothOutEasing(_animationDurationMs);
      }

      _delta = 0;
    }

    final targetZoom = _targetZoom ?? _camera.zoom;
    double zoom;
    bool finished;

    if (_type == _ScrollType.wheel && _startZoom != null && _easing != null) {
      // Smooth interpolation for mouse wheel
      final timeSinceLastWheel =
          currentTimestamp().millisecondsSinceEpoch - _lastWheelEventTime;
      final t = ((timeSinceLastWheel + _wheelEventTimeDiffAdjustment) /
              _animationDurationMs)
          .clamp(0.0, 1.0);
      final k = _easing!(t);
      zoom = (1.0 - k) * _startZoom! + k * targetZoom;
      finished = t >= 1.0;
    } else {
      // Trackpad: apply directly (hardware provides smooth input)
      zoom = targetZoom;
      finished = true;
    }

    zoom = zoom.clamp(minZoom, maxZoom);

    if (zoom != _camera.zoom) {
      final newCenter = _camera.focusedZoomCenter(
        _cursorPosition,
        zoom,
      );
      _controller.moveRaw(
        newCenter,
        zoom,
        hasGesture: true,
        source: MapEventSource.scrollWheel,
      );
    }

    if (finished) {
      _ticker?.stop();
      _tickerActive = false;
      _resetState();
    }
  }

  void _resetState() {
    _startZoom = null;
    _targetZoom = null;
    _prevEase = null;
    _easing = null;
  }

  /// Create a C¹-continuous bezier easing function. When a new wheel event
  /// arrives during an ongoing animation, the new curve starts at the same
  /// velocity the previous curve had, producing smooth chaining.
  _EasingFn _smoothOutEasing(int duration) {
    var easing = _defaultEasing;

    if (_prevEase != null) {
      final currentTime = currentTimestamp().millisecondsSinceEpoch;
      final t = (currentTime - _prevEase!.start) / _prevEase!.duration;
      final prevEasing = _prevEase!.easing;
      final speed = prevEasing((t + 0.01).clamp(0.0, 1.0)) -
          prevEasing(t.clamp(0.0, 1.0));

      // Quick hack to make new bezier that is continuous with last
      final x = 0.27 / math.sqrt(speed * speed + 0.0001) * 0.01;
      final y = math.sqrt((0.27 * 0.27 - x * x).clamp(0.0, double.infinity));
      easing = _bezier(x, y, 0.25, 1);
    }

    _prevEase = _PrevEase(
      start: currentTimestamp().millisecondsSinceEpoch,
      duration: duration.toDouble(),
      easing: easing,
    );

    return easing;
  }

  /// Get the current time. Made public to make timing-dependent code testable.
  @visibleForTesting
  static DateTime Function() currentTimestamp = DateTime.now;
}

class _PrevEase {
  final int start;
  final double duration;
  final _EasingFn easing;

  _PrevEase({
    required this.start,
    required this.duration,
    required this.easing,
  });
}
