name: Bug Report
description: Let us know about something that isn't working
labels: ["needs triage"]
type: Bug
body:
  - type: markdown
    attributes:
      value: "
        # Bug Report

        Thanks for taking the time to fill out this bug report! To help us verify the issue quicker, please include as much information as you can.


        ---


        Before reporting a bug, please:

        * Check if there is already an open or closed issue that is similar to yours

        * Ensure that you have fully read the documentation (both the website and API docs) that relates to the feature(s) you're having problems with

        * Remember that we're volunteers trying our best to help, so please be polite


        ---
        "
  - type: textarea
    id: details
    attributes:
      label: What is the bug?
      description: What were you implementing when you found this issue? What happens when the bug triggers? What do you think should have happened instead? Does it only occur on a specific platform? Please include as much detail as possible, including screenshots and screen-recordings if you can.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How can we reproduce it?
      description: |
        Please include a fully formatted [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) wrapped in a [Dart code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting), otherwise, detail the exact steps to reproduce this issue.
        If you do not include any information here, it will take longer for us to verify your issue.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Do you have a potential solution?
      description: "If so, please detail it: it will make it quicker for us to fix the issue. We also hugely appriciate PRs!"
