name: Feature Request
description: Suggest functionality that you'd like to see
labels: ["P3 (low)"]
type: Feature
body:
  - type: markdown
    attributes:
      value: "
        # Feature Request

        Thanks for taking the time to let us know what you want to see in flutter_map!
        Unfortunately, response times for feature requests are longer than bug reports, as they are lower priority. If you want this functionality implemented quickly, please make a Pull Request to go alongside this feature request.


        ---


        Before requesting a feature, please:

        * Check if there is already an open or closed issue that is similar to yours

        * Ensure that you're using the latest version of flutter_map

        * Ensure that you've read the documentation (both the website and API docs) thoroughly


        ---
        "
  - type: textarea
    id: description
    attributes:
      label: What do you want implemented?
      description: Give as much detail as you can. Include why you need this feature in the first place, and any potential ideas for implementation.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What other alternatives are available?
      description: Have you used any workarounds, for example?
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: additional-info
    attributes:
      label: Can you provide any other information?
      description: Is there anything else you'd like to say?
