/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docsSidebar: [
    {
      type: 'autogenerated', dirName: '.'
    },
    {
      type: 'link',
      label: 'Full API Reference',
      href: 'https://pub.dev/documentation/flutter_map/latest/flutter_map/flutter_map-library.html',
    },
  ],
};
