name: "Branch & PR"
on:
  push:
    branches: ["!master"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  score-package:
    name: "Score Package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install pana
        run: dart pub global activate pana
      - name: Check package score
        run: pana --exit-code-threshold 0 .

  analyse-code:
    name: "Analyse Code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Check lints
        run: dart analyze --fatal-infos --fatal-warnings

  run-tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: ["3.27.0", ""]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.sdk }}
          cache: true
      - name: Run tests with coverage
        run: flutter test -r expanded --coverage
      - name: Run Codecov
        if: ${{ matrix.sdk == '' }}
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-android:
    name: "Build Demo (Android)"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: ["3.27.0", ""]
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Java 21
        uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.sdk }}
          cache: true
      - name: Build Android app
        run: flutter build apk --dart-define=COMMIT_SHA=${{ github.sha }}
      - name: Rename output APK
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/android-demo.apk
      - name: Upload as artifact
        if: ${{ matrix.sdk == '' }}
        uses: actions/upload-artifact@v7
        with:
          path: example/build/app/outputs/apk/release/android-demo.apk
          if-no-files-found: error
          archive: false

  build-windows:
    name: "Build Demo (Windows)"
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - sdk: "3.27.0"
            os: "windows-2022"
          - sdk: ""
            os: "windows-latest"
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.target.sdk }}
          cache: true
      - name: Build Windows app
        run: flutter build windows --dart-define=COMMIT_SHA=${{ github.sha }}
      # No longer necessary: https://github.com/actions/runner-images/pull/13090/changes
      #- name: Install Inno Setup
      #  if: ${{ matrix.target.sdk == '' }}
      #  run: choco install innosetup --yes --no-progress
      - name: Generate app installer
        if: ${{ matrix.target.sdk == '' }}
        run: iscc "windows/installer-config.iss"
      - name: Upload as artifact
        if: ${{ matrix.target.sdk == '' }}
        uses: actions/upload-artifact@v7
        with:
          path: example/build/windows/output/windows-demo.exe
          if-no-files-found: error
          archive: false

  build-web:
    name: "Build Demo (Web)"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: ["3.27.0", ""]
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.sdk }}
          cache: true
      - name: Build web app
        run: flutter build web --wasm --dart-define=COMMIT_SHA=${{ github.sha }}
      - name: Compress web build
        if: ${{ matrix.sdk == '' }}
        run: zip -r web-demo.zip build/web
      - name: Upload as artifact
        uses: actions/upload-artifact@v7
        if: ${{ matrix.sdk == '' }}
        with:
          path: example/web-demo.zip
          if-no-files-found: error
          archive: false
