name: Analyse & Build
on: [push, workflow_dispatch]

jobs:
  package-analysis:
    name: "Analyse Package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Dart Package Analyser
        uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Package Scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          if (( $TOTAL < $TOTAL_MAX ))
          then
            echo Package score less than available score. Improve the score!
            exit 1
          fi

  content-analysis:
    name: "Analyse Contents"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java 17 Environment
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Ensure Correct Flutter Installation
        run: flutter --version
      - name: Get All Dependencies
        run: flutter pub get
      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Check Lints
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Run Tests
        run: flutter test -r expanded

  #check-example-changes:
  #  name: "Check Example Application For Changes"
  #  runs-on: "ubuntu-20.04"
  #  outputs:
  #    example_changed: ${{ steps.check_file_changed.outputs.example_changed }}
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v3
  #      with:
  #        fetch-depth: 2
  #    - name: Compare Commit Diffs
  #      shell: pwsh
  #      id: check_file_changed
  #      run: |
  #        $diff = git diff --name-only HEAD^ HEAD
  #        $SourceDiff = $diff | Where-Object { $_ -match '^example/'}
  #        $HasDiff = $SourceDiff.Length -gt 0
  #        Write-Host "::set-output name=example_changed::$HasDiff"
  #
  #build-example:
  #  name: "Build Example Applications"
  #  runs-on: windows-latest
  #  needs: [check-example-changes, content-analysis, package-analysis]
  #  if: needs.check-example-changes.outputs.example_changed == 'True'
  #  defaults:
  #    run:
  #      working-directory: ./example
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v3
  #    - name: Setup Java 17 Environment
  #      uses: actions/setup-java@v3
  #      with:
  #        distribution: "temurin"
  #        java-version: "17"
  #    - name: Setup Flutter Environment
  #      uses: subosito/flutter-action@v2
  #      with:
  #        channel: "stable"
  #    - name: Ensure Correct Flutter Installation
  #      run: flutter --version
  #    - name: Ensure Clean Flutter Environment
  #      run: flutter clean
  #    - name: Remove Existing Prebuilt Applications
  #      run: Remove-Item "prebuiltExampleApplications" -Recurse -ErrorAction Ignore
  #      working-directory: .
  #    - name: Create Prebuilt Applications (Output) Directory
  #      run: md prebuiltExampleApplications
  #      working-directory: .
  #    - name: Build Android Application
  #      run: flutter build apk --split-per-abi --obfuscate --split-debug-info=/symbols
  #    - name: Move Android Application To Output Directory
  #      run: move "example\build\app\outputs\flutter-apk\app-armeabi-v7a-release.apk" "prebuiltExampleApplications\AndroidApplication.apk"
  #      working-directory: .
  #    - name: Build Windows Application
  #      run: flutter build windows --obfuscate --split-debug-info=/symbols
  #    - name: Archive (ZIP) Windows Application To Output Directory
  #      uses: vimtor/action-zip@v1
  #      with:
  #        files: ./example/build/windows/runner/Release
  #        dest: prebuiltExampleApplications/WindowsApplication.zip
  #    - name: Commit Output Directory
  #      uses: EndBug/add-and-commit@v9.0.1
  #      with:
  #        message: "Built Example Applications"
  #        add: "prebuiltExampleApplications/"
  #        default_author: github_actions
